import { FeynmanCard } from '@/types/feynman';

export const PRESET_CARDS: FeynmanCard[] = [
  // 计算机科学
  {
    id: 'cs-1',
    concept: '时间复杂度',
    category: '计算机科学',
    definition: '描述算法执行时间随输入规模增长的变化趋势，用大O符号表示最坏情况下的上界。',
    realLifeExample: '就像整理书架：逐个检查每本书是O(n)，而用二分查找是O(log n)。',
    commonMistakes: ['把常数因子也计入复杂度', '忽略最坏情况只考虑平均', '混淆时间和空间复杂度'],
    memoryTrick: '"大O是上限，就像保险额度，只保最坏情况"',
    difficulty: 'easy',
  },
  {
    id: 'cs-2',
    concept: '递归',
    category: '计算机科学',
    definition: '函数调用自身来解决问题的编程技巧，包含基线条件（终止条件）和递归条件。',
    realLifeExample: '俄罗斯套娃：每个娃娃里面都有一个更小的自己，直到最小的那个无法再打开。',
    commonMistakes: ['忘记设置基线条件导致无限递归', '重复计算相同子问题', '栈溢出'],
    memoryTrick: '"递归就是套娃，记住什么时候停"',
    difficulty: 'easy',
  },
  {
    id: 'cs-3',
    concept: '哈希表',
    category: '计算机科学',
    definition: '通过哈希函数将键映射到存储位置的数据结构，平均O(1)时间复杂度查找。',
    realLifeExample: '图书馆的索引卡片系统：书名经过编码直接告诉你书放在哪个书架。',
    commonMistakes: ['忽视哈希冲突的处理', '使用糟糕的哈希函数导致分布不均', '忘记处理键的不可变性'],
    memoryTrick: '"哈希就是翻译官，把钥匙变成地址"',
    difficulty: 'easy',
  },
  {
    id: 'cs-4',
    concept: '动态规划',
    category: '计算机科学',
    definition: '将复杂问题分解为重叠子问题，通过存储子问题的解来避免重复计算。',
    realLifeExample: '计算从家到公司的最短路线：记住到每个路口的最短距离，不用每次都重新算。',
    commonMistakes: ['没有正确识别最优子结构', '状态定义不清晰', '空间复杂度优化遗漏'],
    memoryTrick: '"动规就是记账本，算过的不再算"',
    difficulty: 'medium',
  },
  {
    id: 'cs-5',
    concept: 'TCP/IP 协议',
    category: '计算机科学',
    definition: '互联网通信的基础协议栈，TCP负责可靠传输，IP负责寻址和路由。',
    realLifeExample: '寄快递：IP是地址标签决定送到哪，TCP是签收确认确保包裹完整到达。',
    commonMistakes: ['混淆TCP和UDP的使用场景', '不理解三次握手的必要性', '忽略拥塞控制机制'],
    memoryTrick: '"TCP像挂号信，IP像地址标签"',
    difficulty: 'medium',
  },
  // 物理学
  {
    id: 'phy-1',
    concept: '相对论',
    category: '物理学',
    definition: '爱因斯坦提出的物理理论，指出时间、空间、质量都随观察者的运动状态而变化。',
    realLifeExample: 'GPS卫星必须考虑相对论效应：高速运动使卫星上的时钟每天慢7微秒，否则定位会偏差数公里。',
    commonMistakes: ['认为相对论只适用于高速', '混淆狭义和广义相对论', '认为时间膨胀只是错觉'],
    memoryTrick: '"相对论：速度越快，时间越慢，质量越大"',
    difficulty: 'hard',
  },
  {
    id: 'phy-2',
    concept: '量子纠缠',
    category: '物理学',
    definition: '两个粒子形成关联后，无论相距多远，测量其中一个会瞬间影响另一个的状态。',
    realLifeExample: '一对纠缠粒子像一双魔法手套：一只左手套被确认后，另一只无论在哪都是右手套。',
    commonMistakes: ['认为可以用来超光速通信', '混淆纠缠与经典关联', '认为观测创造了结果'],
    memoryTrick: '"纠缠粒子是双胞胎，一个胖了另一个也胖"',
    difficulty: 'hard',
  },
  {
    id: 'phy-3',
    concept: '熵',
    category: '物理学',
    definition: '系统混乱程度的度量，热力学第二定律指出孤立系统的熵永远不会减少。',
    realLifeExample: '房间不收拾会越来越乱，整理需要消耗能量（做功），这就是熵增。',
    commonMistakes: ['把熵等同于能量', '认为熵增可以局部逆转', '混淆信息熵和热力学熵'],
    memoryTrick: '"熵是混乱度，不收拾房间 entropy 增加"',
    difficulty: 'medium',
  },
  // 心理学
  {
    id: 'psy-1',
    concept: '认知偏差',
    category: '心理学',
    definition: '人类思维中的系统性错误，导致判断和决策偏离理性。',
    realLifeExample: '确认偏差：只相信支持自己观点的新闻，忽略反面证据，就像戴着有色眼镜看世界。',
    commonMistakes: ['认为自己免疫于认知偏差', '把所有判断错误都叫认知偏差', '忽视文化差异对偏差的影响'],
    memoryTrick: '"认知偏差：大脑的快捷方式，有时会走弯路"',
    difficulty: 'easy',
  },
  {
    id: 'psy-2',
    concept: '斯德哥尔摩综合征',
    category: '心理学',
    definition: '人质对绑架者产生情感依附和同情的心理现象，源于求生本能和情感隔离。',
    realLifeExample: '被绑架者开始为绑匪辩护，甚至拒绝营救，因为大脑把"不被伤害"解读为"被善待"。',
    commonMistakes: ['把它等同于斯德哥尔摩城市', '认为只发生在绑架场景', '忽视渐进式情感操纵的过程'],
    memoryTrick: '"斯德哥尔摩：危险中的依赖，变成"爱""',
    difficulty: 'medium',
  },
  {
    id: 'psy-3',
    concept: '心流状态',
    category: '心理学',
    definition: '完全沉浸在某项活动中，时间感消失、自我意识降低的最佳体验状态。',
    realLifeExample: '打游戏或编程时突然发现天黑了，完全没注意到过了几个小时。',
    commonMistakes: ['把专注等同于心流', '认为心流只存在于创造性工作', '忽视挑战与技能的平衡'],
    memoryTrick: '"心流：难到有趣，简单到无聊，刚刚好就进去"',
    difficulty: 'easy',
  },
  // 经济学
  {
    id: 'eco-1',
    concept: '边际效用递减',
    category: '经济学',
    definition: '连续消费某种商品时，每增加一单位消费带来的满足感（效用）逐渐减少。',
    realLifeExample: '第一块披萨很香，第二块还行，第五块就腻了。',
    commonMistakes: ['混淆总效用和边际效用', '认为适用于所有商品', '忽略时间因素'],
    memoryTrick: '"边际效用：第一口可乐最爽，越喝越平淡"',
    difficulty: 'easy',
  },
  {
    id: 'eco-2',
    concept: '机会成本',
    category: '经济学',
    definition: '为了选择某个选项而放弃的其他选项中价值最高的那个。',
    realLifeExample: '选择读研的机会成本可能是三年工作经验和工资，不只是学费。',
    commonMistakes: ['只考虑货币成本', '忽略隐性成本', '混淆沉没成本和机会成本'],
    memoryTrick: '"机会成本：选了A，最好的B就是你的代价"',
    difficulty: 'easy',
  },
  {
    id: 'eco-3',
    concept: '通货膨胀',
    category: '经济学',
    definition: '货币购买力下降，一般物价水平持续上涨的经济现象。',
    realLifeExample: '十年前一碗面5元，现在15元，不是面变贵了，是钱变"薄"了。',
    commonMistakes: ['认为所有物价上涨都是通胀', '混淆通胀和通缩', '忽视结构性通胀'],
    memoryTrick: '"通胀：钱变薄了，东西看起来贵了"',
    difficulty: 'easy',
  },
  // 生物学
  {
    id: 'bio-1',
    concept: '自然选择',
    category: '生物学',
    definition: '适应环境的个体更可能生存和繁殖，导致有利特征在种群中逐渐积累。',
    realLifeExample: '长颈鹿的脖子：脖子较长的个体能吃到更多树叶，存活率更高，后代也继承长脖子。',
    commonMistakes: ['认为个体在主动"进化"', '混淆自然选择和随机突变', '认为进化有方向或目标'],
    memoryTrick: '"自然选择：适者生存，不是最强者"',
    difficulty: 'easy',
  },
  {
    id: 'bio-2',
    concept: 'CRISPR',
    category: '生物学',
    definition: '一种基因编辑技术，利用细菌的天然免疫系统精确切割和修改DNA序列。',
    realLifeExample: '像文字处理器的查找替换功能：找到特定基因序列，剪切并替换为新的序列。',
    commonMistakes: ['认为可以任意设计生物', '忽视脱靶效应', '混淆基因治疗和基因增强'],
    memoryTrick: '"CRISPR：DNA的剪刀和胶水"',
    difficulty: 'medium',
  },
  // 哲学
  {
    id: 'phi-1',
    concept: '奥卡姆剃刀',
    category: '哲学',
    definition: '如无必要，勿增实体。在多个解释中选择最简单的那个。',
    realLifeExample: '电脑开不了机，先检查电源线而不是假设被黑客入侵。',
    commonMistakes: ['把它当作绝对真理', '认为简单等于正确', '忽略必要复杂性'],
    memoryTrick: '"奥卡姆剃刀：剃掉多余的假设，保留最简单的解释"',
    difficulty: 'easy',
  },
  {
    id: 'phi-2',
    concept: '忒修斯之船',
    category: '哲学',
    definition: '如果一个物体的所有组成部分都被替换，它还是原来的物体吗？探讨身份同一性。',
    realLifeExample: '你的身体细胞每7年全部更新一次，现在的你还是7年前的你吗？',
    commonMistakes: ['认为有标准答案', '混淆物理同一性和功能同一性', '忽略渐进变化的特性'],
    memoryTrick: '"忒修斯之船：换完所有木板，船还是那条船吗？"',
    difficulty: 'medium',
  },
  // 数学
  {
    id: 'math-1',
    concept: '贝叶斯定理',
    category: '数学',
    definition: '根据新证据更新假设概率的方法：P(A|B) = P(B|A) * P(A) / P(B)。',
    realLifeExample: '体检阳性后患病概率 = 真阳性率 × 患病率 / 阳性总概率。很多人高估阳性后的患病概率。',
    commonMistakes: ['忽略先验概率', '混淆P(A|B)和P(B|A)', '认为概率有记忆性'],
    memoryTrick: '"贝叶斯：新证据 × 旧信念 = 更新后的信念"',
    difficulty: 'medium',
  },
  {
    id: 'math-2',
    concept: '无穷小量',
    category: '数学',
    definition: '微积分中比任何正数都小但不为零的量，用于描述极限过程中的变化率。',
    realLifeExample: '录像中一帧画面：时间间隔趋近于零，但仍然捕捉到物体的瞬时状态。',
    commonMistakes: ['认为无穷小等于零', '混淆无穷小和无穷大', '忽视极限的严格定义'],
    memoryTrick: '"无穷小：小到看不见，但还不是零"',
    difficulty: 'hard',
  },
  // 化学
  {
    id: 'chem-1',
    concept: '催化剂',
    category: '化学',
    definition: '能加速化学反应但自身不被消耗的物质，通过降低反应活化能起作用。',
    realLifeExample: '婚礼主持人：让婚礼顺利进行（加速反应），但婚礼结束后主持人还在（不被消耗）。',
    commonMistakes: ['认为催化剂改变反应平衡', '认为催化剂参与反应被消耗', '忽视催化剂的专一性'],
    memoryTrick: '"催化剂：只帮忙不干活，自己不变"',
    difficulty: 'easy',
  },
  {
    id: 'chem-2',
    concept: '化学键',
    category: '化学',
    definition: '原子之间通过共享或转移电子形成的吸引力，使原子结合成分子或晶体。',
    realLifeExample: '人际关系：离子键像热恋（一方付出），共价键像合作创业（共同投入）。',
    commonMistakes: ['认为化学键是物理绳子', '混淆离子键和共价键', '忽视氢键的特殊性'],
    memoryTrick: '"化学键：原子之间的"关系"，有共享型也有付出型"',
    difficulty: 'easy',
  },
  // 更多计算机科学
  {
    id: 'cs-6',
    concept: 'RESTful API',
    category: '计算机科学',
    definition: '基于HTTP协议的架构风格，使用URL定位资源，HTTP方法定义操作（GET读、POST创、PUT改、DELETE删）。',
    realLifeExample: '餐厅点餐：菜单是URL，点菜是POST，加菜是PUT，退菜是DELETE，看订单是GET。',
    commonMistakes: ['把REST当成协议', '滥用POST做所有操作', '忽视状态码语义'],
    memoryTrick: '"REST：URL是地址，HTTP方法是动作"',
    difficulty: 'easy',
  },
  {
    id: 'cs-7',
    concept: '死锁',
    category: '计算机科学',
    definition: '多个进程互相等待对方释放资源，导致所有进程都无法继续执行。',
    realLifeExample: '两个人面对面走过窄桥，都停下等对方先过，结果谁也过不去。',
    commonMistakes: ['混淆死锁和饥饿', '认为死锁只发生在数据库', '忽视死锁预防策略'],
    memoryTrick: '"死锁：你等我，我等你，大家一起卡死"',
    difficulty: 'medium',
  },
  {
    id: 'cs-8',
    concept: '负载均衡',
    category: '计算机科学',
    definition: '将请求分发到多台服务器，避免单点过载，提高系统可用性和性能。',
    realLifeExample: '超市结账：开通多个收银台，顾客自动分配到人少的队伍。',
    commonMistakes: ['忽视会话保持', '认为负载均衡等于高可用', '选择不合适的算法'],
    memoryTrick: '"负载均衡：别让一个人扛所有活"',
    difficulty: 'easy',
  },
  // 更多心理学
  {
    id: 'psy-4',
    concept: '锚定效应',
    category: '心理学',
    definition: '人们过度依赖第一个获得的信息（锚点）来做后续判断。',
    realLifeExample: '商品标价1000元打折到500元，你觉得很划算，但如果原价就是500元呢？',
    commonMistakes: ['认为自己不受锚定影响', '忽视任意数字都能成为锚', '只适用于价格场景'],
    memoryTrick: '"锚定：第一个数字像船锚，把你的判断拉过去"',
    difficulty: 'easy',
  },
  {
    id: 'psy-5',
    concept: '马斯洛需求层次',
    category: '心理学',
    definition: '人类需求从低到高分为五层：生理、安全、社交、尊重、自我实现，低层满足后才会追求高层。',
    realLifeExample: '饿着肚子的人不会思考人生意义，先吃饱（生理）才能谈理想（自我实现）。',
    commonMistakes: ['认为层次是严格的阶梯', '忽视文化差异', '认为所有人追求相同'],
    memoryTrick: '"马斯洛：先活着，再安全，有朋友，被尊重，最后找意义"',
    difficulty: 'easy',
  },
  // 更多经济学
  {
    id: 'eco-4',
    concept: '复利',
    category: '经济学',
    definition: '利息再生利息，收益呈指数增长，时间越长效果越惊人。',
    realLifeExample: '每天进步1%，一年后是37.78倍；每天退步1%，一年后只剩0.03。',
    commonMistakes: ['忽视时间的重要性', '认为本金比时间重要', '混淆单利和复利'],
    memoryTrick: '"复利：时间越长，滚雪球越大"',
    difficulty: 'easy',
  },
  {
    id: 'eco-5',
    concept: '比较优势',
    category: '经济学',
    definition: '即使一方在所有领域都更强，双方仍可通过专业化各自相对擅长的领域获益。',
    realLifeExample: '医生打字比助理快，但医生看病的机会成本更高，所以让助理打字。',
    commonMistakes: ['混淆绝对优势', '忽视交易成本', '认为弱者没有优势'],
    memoryTrick: '"比较优势：做自己相对擅长的事，大家都能赢"',
    difficulty: 'medium',
  },
  // 更多物理学
  {
    id: 'phy-4',
    concept: '波粒二象性',
    category: '物理学',
    definition: '微观粒子既表现出粒子性（确定位置）又表现出波动性（干涉衍射），取决于观测方式。',
    realLifeExample: '一个人在公司是经理（粒子：确定角色），在家是父母（波：多角色叠加）。',
    commonMistakes: ['认为粒子"变成"波', '认为观测改变物理实在', '混淆概率波和经典波'],
    memoryTrick: '"波粒二象性：看它是波就是波，看它是粒子就是粒子"',
    difficulty: 'hard',
  },
  {
    id: 'phy-5',
    concept: '引力波',
    category: '物理学',
    definition: '加速质量引起的时空涟漪，以光速传播，2015年首次直接探测到。',
    realLifeExample: '把时空比作蹦床，大质量天体（如黑洞）碰撞就像在蹦床上跳跃，产生涟漪。',
    commonMistakes: ['认为是声波', '认为可以用来通信', '忽视探测的极端难度'],
    memoryTrick: '"引力波：时空的涟漪，黑洞跳舞产生的"',
    difficulty: 'medium',
  },
  // 更多哲学
  {
    id: 'phi-3',
    concept: '囚徒困境',
    category: '哲学',
    definition: '博弈论经典模型，两个理性个体选择不合作反而比合作得到更差结果。',
    realLifeExample: '两个公司打价格战：都不降价都有利润，但都想抢市场降价，最后都亏损。',
    commonMistakes: ['认为理性必然导致合作', '忽视重复博弈', '混淆单次和多次博弈'],
    memoryTrick: '"囚徒困境：各自为营，两败俱伤；合作共赢，皆大欢喜"',
    difficulty: 'medium',
  },
  {
    id: 'phi-4',
    concept: '怀疑主义',
    category: '哲学',
    definition: '对知识的确定性持怀疑态度，认为我们无法获得绝对可靠的知识。',
    realLifeExample: '你怎么确定你不是在做梦？笛卡尔由此推导出"我思故我在"。',
    commonMistakes: ['把怀疑主义等同于虚无主义', '认为怀疑一切就无法行动', '忽视怀疑主义的方法论价值'],
    memoryTrick: '"怀疑主义：什么都怀疑一下，但怀疑本身不怀疑"',
    difficulty: 'medium',
  },
  // 更多数学
  {
    id: 'math-3',
    concept: '中心极限定理',
    category: '数学',
    definition: '大量独立随机变量之和近似服从正态分布，无论原始分布是什么。',
    realLifeExample: '掷骰子一次是均匀分布，但掷100次求平均值，结果接近钟形曲线。',
    commonMistakes: ['认为任何分布都会变成正态', '忽视独立同分布条件', '混淆样本和总体'],
    memoryTrick: '"中心极限：加多了，什么分布都变钟形"',
    difficulty: 'medium',
  },
  {
    id: 'math-4',
    concept: '虚数',
    category: '数学',
    definition: '定义i² = -1的数，扩展了实数系统，在电学和量子力学中有广泛应用。',
    realLifeExample: '就像从1维数轴扩展到2维平面，虚数给数学增加了"方向"。',
    commonMistakes: ['认为虚数"不存在"', '混淆虚数和复数', '忽视几何解释'],
    memoryTrick: '"虚数：-1的平方根，数学的想象力"',
    difficulty: 'medium',
  },
  // 更多化学
  {
    id: 'chem-3',
    concept: '氧化还原',
    category: '化学',
    definition: '电子转移的化学反应，氧化是失去电子，还原是获得电子。',
    realLifeExample: '电池放电：负极材料失去电子（氧化），正极材料获得电子（还原）。',
    commonMistakes: ['认为氧化必须涉及氧', '混淆氧化剂和还原剂', '忽视半反应'],
    memoryTrick: '"氧化还原：失去电子是氧化（LEO），得到电子是还原（GER）"',
    difficulty: 'easy',
  },
  {
    id: 'chem-4',
    concept: '同位素',
    category: '化学',
    definition: '质子数相同但中子数不同的原子，化学性质相似但物理性质（如质量）不同。',
    realLifeExample: '碳-12和碳-14：都是碳元素，但碳-14多两个中子，具有放射性用于考古测年。',
    commonMistakes: ['认为同位素是不同元素', '混淆同位素和同素异形体', '忽视放射性差异'],
    memoryTrick: '"同位素：同样的质子，不同的中子，性格相似体重不同"',
    difficulty: 'easy',
  },
  // 更多生物学
  {
    id: 'bio-3',
    concept: '表观遗传学',
    category: '生物学',
    definition: '不改变DNA序列但影响基因表达的遗传机制，如DNA甲基化和组蛋白修饰。',
    realLifeExample: '同卵双胞胎基因相同，但随着年龄增长生活方式不同，基因表达逐渐产生差异。',
    commonMistakes: ['认为表观遗传改变DNA序列', '认为不能跨代遗传', '忽视环境因素'],
    memoryTrick: '"表观遗传：同样的剧本，不同的演出"',
    difficulty: 'hard',
  },
  {
    id: 'bio-4',
    concept: '光合作用',
    category: '生物学',
    definition: '植物利用光能将二氧化碳和水转化为葡萄糖和氧气的过程。',
    realLifeExample: '太阳能板：植物是世界上最高效的太阳能转换器，把光能变成化学能存储。',
    commonMistakes: ['认为只发生在白天', '认为动物也能光合作用', '混淆光合作用和呼吸作用'],
    memoryTrick: '"光合作用：吸CO2喝水晒太阳，吐出氧气存糖"',
    difficulty: 'easy',
  },
];